version: '3.8'

services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    command: ./start.sh

  dashboard-backend:
    build: ./dashboard/backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./dashboard/backend:/app

  dashboard-frontend:
    build: ./dashboard/frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./dashboard/frontend:/app
    depends_on:
      - dashboard-backend
